[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "BUW39Wm8Q3cXfkbQ6aesRKARc3bKxUJL3vHWFMn6ntRz"

[programs.devnet]
solana_twitter = "BUW39Wm8Q3cXfkbQ6aesRKARc3bKxUJL3vHWFMn6ntRz"

[programs.mainnet]
solana_twitter = "BUW39Wm8Q3cXfkbQ6aesRKARc3bKxUJL3vHWFMn6ntRz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/terenceco/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
